// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5I_S_JI1AA528r8l80ftpgTFJ9vCU3LA',
    appId: '1:867398915045:web:08e2ed62d33920c806d50c',
    messagingSenderId: '867398915045',
    projectId: 'student-bf399',
    authDomain: 'student-bf399.firebaseapp.com',
    storageBucket: 'student-bf399.appspot.com',
    measurementId: 'G-8X2KGSV2PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtA8_zUEuw9bqLT3q65bPdaXAmtEt7NVE',
    appId: '1:867398915045:android:f3f46123bb0f367d06d50c',
    messagingSenderId: '867398915045',
    projectId: 'student-bf399',
    storageBucket: 'student-bf399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaFjQyW0R40gH1CunjXdFIPAO3vsMWNdw',
    appId: '1:867398915045:ios:9a890fb92859ccd106d50c',
    messagingSenderId: '867398915045',
    projectId: 'student-bf399',
    storageBucket: 'student-bf399.appspot.com',
    iosClientId: '867398915045-guc0hqe1bnddk45vsl485q2op9uf9euq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaFjQyW0R40gH1CunjXdFIPAO3vsMWNdw',
    appId: '1:867398915045:ios:9a890fb92859ccd106d50c',
    messagingSenderId: '867398915045',
    projectId: 'student-bf399',
    storageBucket: 'student-bf399.appspot.com',
    iosClientId: '867398915045-guc0hqe1bnddk45vsl485q2op9uf9euq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
